### ISSUE TITLE
NeoForge Support? 

### ISSUE THREAD

**Issue by iekiekkeikei** [FerrinEmber/MobSpiderClimb#2]
Especially after 1.21, NeoForge mod development is more active than Forge, so I would like to have support for NeoForge!

**Comment by FerrinEmber** [comment]
Neoforge support is planned for 1.21! The mod's most active version is currently 1.20.1, as it is primarily being developed for a 1.20.1 forge modpack. However, once that is done, neoforge will likely be the default forge in 1.21 and beyond
